/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 * 
 * @author SUS
 */
public class warung extends javax.swing.JFrame {
    String menu;
    int harga, pesanan,total;
    public warung() {
        initComponents();
        hasil.setText("" + pesanan);
        tambah.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                pesanan++;
                hasil.setText(Integer.toString(pesanan));
            }
        });
        kurang.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (pesanan > 0) {
                    pesanan--;
                    hasil.setText(Integer.toString(pesanan));
                }
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        gambar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jumlah = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        beli = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        nama = new javax.swing.JLabel();
        isijmlhp = new javax.swing.JTextField();
        jmlhp = new javax.swing.JLabel();
        isinama = new javax.swing.JTextField();
        lharga = new javax.swing.JLabel();
        isiharga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        isitotal = new javax.swing.JTextField();
        capcay = new javax.swing.JRadioButton();
        kwetiau = new javax.swing.JRadioButton();
        fuyunghai = new javax.swing.JRadioButton();
        koloke = new javax.swing.JRadioButton();
        bakmie = new javax.swing.JRadioButton();
        sopiga = new javax.swing.JRadioButton();
        udang = new javax.swing.JRadioButton();
        ayam = new javax.swing.JRadioButton();
        kepiting = new javax.swing.JRadioButton();
        nasgor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        judul.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 38)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("CHINESE FOOD");

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas2/ed4eafa02299bc651b536c68dbdfac23-removebg-preview (1).png"))); // NOI18N
        gambar.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 100));

        jumlah.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jumlah.setForeground(new java.awt.Color(255, 255, 255));
        jumlah.setText("Jumlah Beli");

        tambah.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 204, 0));
        tambah.setText("+");

        kurang.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        kurang.setForeground(new java.awt.Color(255, 204, 0));
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });

        hasil.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        hasil.setForeground(new java.awt.Color(255, 204, 0));
        hasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        beli.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        beli.setForeground(new java.awt.Color(255, 204, 0));
        beli.setText("BELI");
        beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 204, 0));
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        nama.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        nama.setText("Nama Pesanan");

        isijmlhp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isijmlhpActionPerformed(evt);
            }
        });

        jmlhp.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jmlhp.setText("Jumlah Pesanan");

        isinama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isinamaActionPerformed(evt);
            }
        });

        lharga.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lharga.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Total");

        isitotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isitotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nama)
                                    .addComponent(lharga)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(beli)))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isiharga, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hapus)
                                    .addComponent(isinama, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jmlhp)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isitotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(isijmlhp, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jumlah))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah)
                    .addComponent(beli)
                    .addComponent(hapus))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama)
                    .addComponent(isinama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(isiharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lharga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jmlhp)
                            .addComponent(isijmlhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(isitotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        buttonGroup1.add(capcay);
        capcay.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        capcay.setForeground(new java.awt.Color(255, 204, 0));
        capcay.setText("Capcay");

        buttonGroup1.add(kwetiau);
        kwetiau.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        kwetiau.setForeground(new java.awt.Color(255, 204, 0));
        kwetiau.setText("Kwetiau");

        buttonGroup1.add(fuyunghai);
        fuyunghai.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        fuyunghai.setForeground(new java.awt.Color(255, 204, 0));
        fuyunghai.setText("Fuyunghai");
        fuyunghai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuyunghaiActionPerformed(evt);
            }
        });

        buttonGroup1.add(koloke);
        koloke.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        koloke.setForeground(new java.awt.Color(255, 204, 0));
        koloke.setText("Koloke");

        buttonGroup1.add(bakmie);
        bakmie.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        bakmie.setForeground(new java.awt.Color(255, 204, 0));
        bakmie.setText("Bakmie");

        buttonGroup1.add(sopiga);
        sopiga.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        sopiga.setForeground(new java.awt.Color(255, 204, 0));
        sopiga.setText("Sop Iga");

        buttonGroup1.add(udang);
        udang.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        udang.setForeground(new java.awt.Color(255, 204, 0));
        udang.setText("Udang");
        udang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udangActionPerformed(evt);
            }
        });

        buttonGroup1.add(ayam);
        ayam.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        ayam.setForeground(new java.awt.Color(255, 204, 0));
        ayam.setText("Ayam");

        buttonGroup1.add(kepiting);
        kepiting.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        kepiting.setForeground(new java.awt.Color(255, 204, 0));
        kepiting.setText("Kepiting");

        buttonGroup1.add(nasgor);
        nasgor.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        nasgor.setForeground(new java.awt.Color(255, 204, 0));
        nasgor.setText("Nasi Goreng");
        nasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasgorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kwetiau)
                    .addComponent(capcay)
                    .addComponent(fuyunghai)
                    .addComponent(udang)
                    .addComponent(kepiting))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nasgor)
                    .addComponent(ayam)
                    .addComponent(bakmie)
                    .addComponent(koloke)
                    .addComponent(sopiga))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capcay)
                    .addComponent(koloke))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kwetiau)
                    .addComponent(bakmie))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuyunghai)
                    .addComponent(sopiga))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(udang)
                    .addComponent(ayam))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kepiting)
                    .addComponent(nasgor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fuyunghaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuyunghaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuyunghaiActionPerformed

    private void udangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udangActionPerformed

    private void nasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasgorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nasgorActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        buttonGroup1.clearSelection();
        isinama.setText("");
        hasil.setText("");
        isiharga.setText("");
        isijmlhp.setText("");
        isitotal.setText("");

    }//GEN-LAST:event_hapusActionPerformed

    private void beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliActionPerformed
        if (capcay.isSelected()){
            menu = "Capcay";
            harga = 20000;
        } else if (kwetiau.isSelected()){
            menu = "Kwetiau";
            harga = 15000;
        }else if(fuyunghai.isSelected()){
            menu = "Fuyunghai";
            harga = 10000;
        }else if(udang.isSelected()){
            menu = "Udang";
            harga = 20000;
        }else if(kepiting.isSelected()){
            menu = "Kepiting";
            harga = 25000;
        }else if(koloke.isSelected()){
            menu = "Koloke";
            harga = 20000;
        }else if(bakmie.isSelected()){
            menu = "Bakmie";
            harga = 15000;
        }else if(sopiga.isSelected()){
            menu = "Sop Iga";
            harga = 20000;
        }else if(ayam.isSelected()){
            menu = "Ayam";
            harga = 20000;
        }else if(nasgor.isSelected()){
            menu = "Nasi Goreng";
            harga = 15000;
        }else{
            JOptionPane.showMessageDialog(this, "SILAHKAN MEMILIH MENU", "ERROR", JOptionPane.ERROR_MESSAGE);
        }     

        pesanan = Integer.parseInt(hasil.getText());
        total = pesanan * harga;
        isinama.setText(menu);
        isiharga.setText(String.valueOf(harga));
        isijmlhp.setText(String.valueOf(pesanan));
        isitotal.setText(String.valueOf(total));
        
        
    }//GEN-LAST:event_beliActionPerformed

    private void isijmlhpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isijmlhpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isijmlhpActionPerformed

    private void isitotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isitotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isitotalActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kurangActionPerformed

    private void isinamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isinamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isinamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new warung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ayam;
    private javax.swing.JRadioButton bakmie;
    private javax.swing.JButton beli;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton capcay;
    private javax.swing.JRadioButton fuyunghai;
    private javax.swing.JLabel gambar;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField isiharga;
    private javax.swing.JTextField isijmlhp;
    private javax.swing.JTextField isinama;
    private javax.swing.JTextField isitotal;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jmlhp;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel jumlah;
    private javax.swing.JRadioButton kepiting;
    private javax.swing.JRadioButton koloke;
    private javax.swing.JButton kurang;
    private javax.swing.JRadioButton kwetiau;
    private javax.swing.JLabel lharga;
    private javax.swing.JLabel nama;
    private javax.swing.JRadioButton nasgor;
    private javax.swing.JRadioButton sopiga;
    private javax.swing.JButton tambah;
    private javax.swing.JRadioButton udang;
    // End of variables declaration//GEN-END:variables
}
